[package]
name = "mkarm64image"
version = "0.1.0"
authors = ["Rose Hudson <thomhuds@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
clap = "3.0.0-beta.1"
